//
//  FARGlobalConst.h
//  Fairy-iOS
//
//  Created by 周孙静 on 2020/11/28.
//


#import <Foundation/Foundation.h>

FOUNDATION_EXTERN NSString *const FAR_STACK_KEY;

FOUNDATION_EXTERN NSString *const FAR_ADD_FUNC;
FOUNDATION_EXTERN NSString *const FAR_SUB_FUNC;
FOUNDATION_EXTERN NSString *const FAR_MUL_FUNC;
FOUNDATION_EXTERN NSString *const FAR_DIV_FUNC;
FOUNDATION_EXTERN NSString *const FAR_MOD_FUNC;
FOUNDATION_EXTERN NSString *const FAR_CMPGT_FUNC;
FOUNDATION_EXTERN NSString *const FAR_CMPLT_FUNC;
FOUNDATION_EXTERN NSString *const FAR_CMPGE_FUNC;
FOUNDATION_EXTERN NSString *const FAR_CMPLE_FUNC;
FOUNDATION_EXTERN NSString *const FAR_CMPEQ_FUNC;
FOUNDATION_EXTERN NSString *const FAR_CMPNE_FUNC;
FOUNDATION_EXTERN NSString *const FAR_CMPOR_FUNC;
FOUNDATION_EXTERN NSString *const FAR_AND_FUNC;
FOUNDATION_EXTERN NSString *const FAR_NEG_FUNC;
FOUNDATION_EXTERN NSString *const FAR_NOT_FUNC;

FOUNDATION_EXTERN NSString *const FAR_OPER_1;
FOUNDATION_EXTERN NSString *const FAR_OPER_2;

FOUNDATION_EXTERN NSString *const FAR_CLASS_SELF;
FOUNDATION_EXTERN NSString *const FAR_CLASS_SUPER;

FOUNDATION_EXTERN NSString *const FAR_TRAILING_CLOSURE;

FOUNDATION_EXTERN NSString *const FAR_MAIN_CODE;
FOUNDATION_EXTERN NSString *const FAR_NATIVE_OBJ;
FOUNDATION_EXTERN NSString *const FAR_TO_NATIVE_FUNC;


FOUNDATION_EXTERN NSString *const FAR_INIT_FUNC;
FOUNDATION_EXTERN NSString *const FAR_SELF_INS;
FOUNDATION_EXTERN NSString *const FAR_SUPER_INS;
FOUNDATION_EXTERN NSString *const FAR_NIL;

FOUNDATION_EXTERN NSString *const FAR_ARRAY_PUSH;
FOUNDATION_EXTERN NSString *const FAR_ARRAY_REMOVE;
FOUNDATION_EXTERN NSString *const FAR_ARRAY_DIC_SET;
FOUNDATION_EXTERN NSString *const FAR_ARRAY_DIC_GET;
FOUNDATION_EXTERN NSString *const FAR_ARRAY_COUNT;
FOUNDATION_EXTERN NSString *const FAR_ARRAY_DIC_VALUE;
FOUNDATION_EXTERN NSString *const FAR_ARRAY_INDEX;
FOUNDATION_EXTERN NSString *const FAR_ARRAY_PUSH_AT_INDEX;
FOUNDATION_EXTERN NSString *const FAR_DIC_KEY;

FOUNDATION_EXTERN NSString *const FAR_INNER_NATIVE_OBJ;

